login/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#home'
  # get '/home' , to: 'static_pages/home'
  get '/help' , to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

login/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

login/app/models/user.rb
class User < ApplicationRecord
	before_save {self.email = self.email.downcase}
	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 250},
			   format: {with: VALID_EMAIL_REGEX},
			   uniqueness: { case_sensitive: false}

	validates :password, length: {minimum: 6},
				presence: true, allow_nil: true
	has_secure_password

	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
	    BCrypt::Password.create(string, cost: cost)
	end
end

login/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

login/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in user
  		redirect_to user
  	else
  		flash.now[:danger] = "Invalid email/password combination"
  		render 'new'
  	end
  end
  def destroy
  	log_out
  	redirect_to login_path
  end
end

login/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

login/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :logged_in_user, only:[:destroy, :index,:edit, :update]
  before_action :correct_user, only:[:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @user = User.all
  end

  def new
  	@user = User.new
  end
  
  def show
  	@user = User.find(params[:id])
  	# debugger
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		log_in user
  		flash[:success] = "Welcome "
  		redirect_back_to
  	else
  		render 'new'
  	end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:sucess] = "Profile Updated"
      redirect_back_or user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Successfully deleted the user"
    redirect_to users_url    
  end

  private
  	def user_params
  		params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_path
    end
  end

  def correct_user 
    @user = User.find(params[:id])
    redirect_to root_path unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end
end

login/app/helpers/application_helper.rb
module ApplicationHelper
end

login/app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id		
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])		
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
	  	@current_user = nil
	end

	def current_user?(user)
		user == current_user		
	end

	def redirect_back_or(default)
		redirect_to(session[:forwarding_url] || default)
		session.delete(:forwarding_url)
	end

	def store_location
		session[:forwarding_url] = request.original_url if request.get?
	end
end

login/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

login/app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options = { size: 80 })
	    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
	    size = options[:size]
	    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
	    image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end 
end

login/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Ankit Amrit Raj</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

login/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
		<div class="container-fluid">
  			<%= link_to "Sample App", root_path, id: "logo" %>
  			<nav>
  				<ul class="nav navbar-nav navbar-right">
  					<li><%= link_to "Home", root_path%></li>  	
  					<li><%= link_to "Help", help_path%></li>
            <% if logged_in? %>
              <li><%=link_to "Users", users_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class = "divider"></li>
                  <li><%= link_to "Log out", logout_path, method: "delete" %>
                  </li>
                </ul>  
              </li>
            <% else %>
              <li> <%= link_to "Log In", login_path %> </li>
            <% end %>
            
  				</ul>
  			</nav>
		</div>
</header>

login/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/header'%>
  	<div class="container">
	  	<%flash.each do |key, value|%>
	  		<div class="alert alert-<%=key%>"> 
	  			<%= value%> to the application
	  		</div>
	  	<%end%>
	    <%= yield %>
  	</div>

  	<%= render 'layouts/footer' %>

  	<%= debug(params) if Rails.env.development? %>
  </body>
</html>

login/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id = "error explanation">
		<div class = "alert alert-danger">
			The form contains <%= pluralize(@user.errors.count, "error") %>
		</div> 
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
			<li><%= msg %> </li>
			<% end %>
		</ul>
	</div>
<% end %>

login/app/views/static_pages/about.html.erb
<%provide(:title, "About") %>


    <h1>About</h1>
    <p>
      The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
      Tutorial</em></a> is a
      <a href="http://www.railstutorial.org/book">book</a> and
      <a href="http://screencasts.railstutorial.org/">screencast series</a>
      to teach web development with
      <a href="http://rubyonrails.org/">Ruby on Rails</a>.
      This is the sample application for the tutorial.
    </p>

login/app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1> Contact </h1>

<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/contact">contact page</a>.
</p>

login/app/views/static_pages/help.html.erb
<%provide(:title, "Help") %>


	<h1>Help</h1>
	<p>
	  Get help on the Ruby on Rails Tutorial at the
	  <a href="http://www.railstutorial.org/help">Rails Tutorial help
	  page</a>.
	  To get help on this sample app, see the
	  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails
	  Tutorial</em> book</a>.
	</p>

login/app/views/static_pages/home.html.erb
<%provide(:title, "Home") %>

<div class= "center jumbotron">
	<h1>Welcome to Sample App</h1>
	<h2>
	  This is the home page for the
	  <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
	  sample application.
	</h2>

	<%= link_to "Sign Up now", signup_path, class: "btn btn-lng btn-primary "%>
</div>


<%= link_to image_tag("rails.png", alt: "Rails Logo"), 'http://rubyonrails.org/' %>

login/app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile </h1>

<div class = "row">
	<div class = "col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>

			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :email %>
			<%= f.email_field :email, class:'form-control' %>

			<%= f.label :password %>
			<%= f.password_field :password , class: 'form-control' %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>

			<%= f.submit "Save Changes", class: "btn btn-lng btn-primary" %>
		<% end %>

		<div class="gravatar_edit">
			<%= gravatar_for @user %>
			<a href="http://gravatar.com/emails" target= "blank	">Change</a>
		</div>
	</div>
</div>

login/app/views/users/index.html.erb
<% provide(:title, "All Users") %>
<h1>All Users </h1>

<ul class="users">
	<% @user.each do |user| %>
		<li>
			<%= gravatar_for user, size: 50 %>
			<%= link_to user.name, user%>
			<% if current_user.admin? && !current_user?(user) %> | <%= link_to "Delete", user, method: :delete, data: {confirm: "You Sure?"} %>
			<% end %>
		</li>
	<% end %>
</ul>	

login/app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<h1>Sign Up</h1>

<div class= "row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>

			<%= render 'shared/error_messages' %>
			<%= f.label :name%>
			<%= f.text_field :name ,class: 'form-control'%>

			<%= f.label :email %>
			<%= f.text_field :email, class: 'form-control'%>

			<%= f.label :password%>
			<%= f.password_field :password, class: 'form-control'%>

			<%= f.label :password_confirmation , "Confirmation" %>
			<%= f.password_field :password_conformation, class: 'form-control'%>

			<%= f.submit "Create my account", class: "btn btn-lng btn-primary" %>

		<%end%>
	</div>
</div>

login/app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class = "row">
	<aside class = "col-md-4">
		<section class = "user_info">
			<h1> 
				<%= gravatar_for(@user) %>
				<%= @user.name%>
			</h1>
		</section>
	</aside>
</div>